apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ibrahimalish/go-backend
  newTag: 9ee2eefb2099b1a1cc84dba85a528141a43ed0e2
- name: ibrahimalish/node-frontend
  newTag: 9ee2eefb2099b1a1cc84dba85a528141a43ed0e2
