apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ibrahimalish/go-backend
  newTag: 947bd6636acb8e0a6ab01044e3ca384e44979950
- name: ibrahimalish/node-frontend
  newTag: 947bd6636acb8e0a6ab01044e3ca384e44979950
